/*
 * @copyRight by iHealthScreen
 */
const images = {
  auth_background: require('../assets/img/background.png'),
  app_icon: require('../assets/icon/app_icon.png'),
  login_logo: require('../assets/icon/signin_logo.png'),
  patient_info: require('../assets/img/patient_info.png'),
  male_icon: require('../assets/icon/male.png'),
  female_icon: require('../assets/icon/female.png'),
  home: require('../assets/icon/home.png'),
  more: require('../assets/icon/more.png'),
  history: require('../assets/icon/history.png'),
  plus: require('../assets/icon/plus.png'),
  doc_specialist: require('../assets/icon/doc_specialist.png'),
  profile_demo: require('../assets/icon/profile_img.png'),
  notification: require('../assets/icon/notification.png'),
  filter1: require('../assets/icon/filter1.png'),
  filter2: require('../assets/icon/filter2.png'),
  heart: require('../assets/img/heart.png'),
  lung: require('../assets/img/lung.png'),
  stomach: require('../assets/img/stomach.png'),
  brain: require('../assets/img/brain.png'),
  teeth: require('../assets/img/teeth.png'),
  user: require('../assets/icon/user.png'),
  users: require('../assets/icon/users.png'),
  love: require('../assets/icon/heart.png'),
  history1: require('../assets/icon/history1.png'),
  settings: require('../assets/icon/settings.png'),
  policy: require('../assets/icon/policy.png'),
  faq: require('../assets/icon/faq.png'),
  info: require('../assets/icon/info.png'),
  logout: require('../assets/icon/logout.png'),
  terms: require('../assets/icon/terms.png'),
  dollar: require('../assets/icon/dollar.png'),
  // heartLogo: require('src/images/heart.png'),
  // diabetes: require('src/images/diabetes-logo.png'),
  // stroke: require('src/images/stroke-logo.png'),
  // heartAtack: require('src/images/HeartAttack.png'),
};

export default images;
