/*
 * @copyRight by iHealthScreen
 */
const Routes = {
  SPLASH: 'Splash',
  LOADER: 'Loader',
  HOME: 'Home',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  INTRO: 'Intro',
  FIRSTPAGE: 'Info',
  VERIFICATION: 'VERIFICATION',
  FORGOT_PASSWORD: 'Forgot Password',
  RESET_PASSWORD: 'Reset Password',
  MANAGE_PATIENT: 'Manage Patient',
  FAV_DOCTOR: 'Favourite Doctor',
  PATIENT_DASHBOARD: 'Patient Dashboard',
  PATIENT_HOME: 'Patient Home',
  DOCTOR_DASHBOARD: 'Doctor Dashboard',
  BACK: 'Back',
  HOME: 'Home',
  PATIENT_APPOINTMENT: 'Patient Appointment',
  PATIENT_APPOINTMENT_CREATE: 'Create Appointment',
  DOCTOR_DETAILS: 'Doctor Details',
  JOURNAL: 'Journal',
  MORE: 'More',
  NOTIFICATION: 'Notification',
  JOURNAL_LIST: 'Journal List',
  JOURNAL_DETAILS: 'Journal Details',
  DOCTOR: 'Doctor',
  MY_PRESCRIPTION: 'My Prescription',
  APPOINTMENT_HISTORY: 'Appointment History',
  APPOINTMENT_DETAILS: 'Appointment Details',
  DOCTOR_PROFILE: 'My Account',
  DOCTOR_PROFILE_EDIT: 'Doctor Profile Edit',
  DOCTOR_ACCOUNT_INFO_DETAILS: 'Doctor Account Info Details',
  PATIENT_PROFILE: 'Patient Account',
  PATIENT_PROFILE_EDIT: 'Patient Profile Edit',
  PATIENT_PERSONAL_INFO_DETAILS: 'Patient Personal Info Details',
  SUPPORT: 'Support',
  DOCTORS_TODAY_SCHEDULE: 'Todays Schedule',
  DOCTOR_WALLET: 'Doctor Wallet',
  PAYMENT: 'Payment',
  PAYMENT_WEB: 'Payment Web',
  PAYMENT_SUCCESS: 'Payment Success',
  PAYMENT_HISTORY: 'Payment History',
  CUR_APPOINTMENT: 'Current Appointment',
  VIDEO: 'Video',
  CREATE_SCHEDULE: 'Create Schedule',
  COMPONENT_LIST: 'Component List',
  PATIENT_REQUEST: 'Patient Request',
  PATIENT_MESSAGE: 'Patient Message',
  DOCTOR_LIST_OF_SCHEDULE: 'Doctor List Of Schedule',
  CHAT: 'Chat',
  DOCTOR_WALLET_WITHDRAW: 'Doctor Wallet Withdraw',
  FLAT_LIST: 'Flat List',
  CREATE_PRESCRIPTION: 'Create Prescription',
  VIEW_PRESCRIPTION: 'View Prescription',
  FORGET_PASSWORD: 'Forget Password',
  SET_PASSWORD: 'Set Password',
  RATING: 'Doctor Rating',
  TEST: 'Test',
  SCHEDULE_SUCCESS: 'Schedule Success',
  FORGET_PASS: 'Forget Pass',
  PREDICTIONS_WEB: 'Predictions App WebView',
  PREDICTION_APPS: 'Prediction Apps',
  PREDICTION_APPS_RESULT: 'Prediction Apps RESULT',
  DIABETES_APP: 'Diabetes Prediction App',
  DIABETES_APP_RESULT: 'Diabetes App Result',
  CVD_APP: 'CVD Prediction App',
  STROKE_APP: 'Stroke Prediction App',
  HEART_ATTACK_APP: 'Heart Attack Prediction App',
  APPLIED_OFFER_LIST: 'Applied Offer List',
};
export default Routes;
